"""Utilities for apps to integrate with and extend the existing Nautobot UI."""

from nautobot.core.choices import ButtonColorChoices
from nautobot.core.ui.base import PermissionsMixin
from nautobot.core.ui.breadcrumbs import (
    AncestorsBreadcrumbs,
    AncestorsInstanceBreadcrumbItem,
    BaseBreadcrumbItem,
    Breadcrumbs,
    context_object_attr,
    InstanceBreadcrumbItem,
    InstanceParentBreadcrumbItem,
    ModelBreadcrumbItem,
    ViewNameBreadcrumbItem,
)
from nautobot.core.ui.bulk_buttons import (
    BaseBulkButton,
    BulkDeleteButton,
    BulkDisconnectButton,
    BulkEditButton,
    BulkRenameButton,
)
from nautobot.core.ui.choices import (
    EChartsThemeColors,
    EChartsTypeChoices,
    LayoutChoices,
    NavigationIconChoices,
    NavigationWeightChoices,
    SectionChoices,
)
from nautobot.core.ui.echarts import (
    EChartsBase,
    queryset_to_nested_dict_keys_as_series,
    queryset_to_nested_dict_records_as_series,
)
from nautobot.core.ui.homepage import (
    HomePageBase,
    HomePageGroup,
    HomePageItem,
    HomePagePanel,
)
from nautobot.core.ui.nav import (
    NavMenuAddButton,
    NavMenuBase,
    NavMenuButton,
    NavMenuGroup,
    NavMenuImportButton,
    NavMenuItem,
    NavMenuTab,
)
from nautobot.core.ui.object_detail import (
    AsyncStatsPanel,
    BaseTextPanel,
    Button,
    Component,
    ConnectedEndpointsPanel,
    ConnectionPanel,
    DataTablePanel,
    DistinctViewTab,
    DropdownButton,
    EChartsPanel,
    FormButton,
    GroupedKeyValueTablePanel,
    KeyValueTablePanel,
    ObjectDetailContent,
    ObjectFieldsPanel,
    ObjectsTablePanel,
    ObjectTextPanel,
    Panel,
    PostButton,
    StatsPanel,
    Tab,
    TextPanel,
)
from nautobot.core.ui.object_form import (
    AllOf,
    AnyOf,
    Condition,
    Contributed,
    ContributedFieldsPanel,
    FieldGroup,
    FormComponent,
    FormField,
    FormLayout,
    FormLayoutMixin,
    FormPanel,
    InlineFields,
    Not,
    Omitted,
    StaticField,
    TabbedGroups,
    When,
)
from nautobot.core.ui.titles import Titles
from nautobot.core.ui.utils import (
    flatten_context,
    get_absolute_url,
    render_component_template,
)
from nautobot.extras.choices import BannerClassChoices
from nautobot.extras.plugins import Banner, TemplateExtension

__all__ = (
    "AllOf",
    "AncestorsBreadcrumbs",
    "AncestorsInstanceBreadcrumbItem",
    "AnyOf",
    "AsyncStatsPanel",
    "Banner",
    "BannerClassChoices",
    "BaseBreadcrumbItem",
    "BaseBulkButton",
    "BaseTextPanel",
    "Breadcrumbs",
    "BulkDeleteButton",
    "BulkDisconnectButton",
    "BulkEditButton",
    "BulkRenameButton",
    "Button",
    "ButtonColorChoices",
    "Component",
    "Condition",
    "ConnectedEndpointsPanel",
    "ConnectionPanel",
    "Contributed",
    "ContributedFieldsPanel",
    "DataTablePanel",
    "DistinctViewTab",
    "DropdownButton",
    "EChartsBase",
    "EChartsPanel",
    "EChartsThemeColors",
    "EChartsTypeChoices",
    "FieldGroup",
    "FormButton",
    "FormComponent",
    "FormField",
    "FormLayout",
    "FormLayoutMixin",
    "FormPanel",
    "GroupedKeyValueTablePanel",
    "HomePageBase",
    "HomePageGroup",
    "HomePageItem",
    "HomePagePanel",
    "InlineFields",
    "InstanceBreadcrumbItem",
    "InstanceParentBreadcrumbItem",
    "KeyValueTablePanel",
    "LayoutChoices",
    "ModelBreadcrumbItem",
    "NavMenuAddButton",
    "NavMenuBase",
    "NavMenuButton",
    "NavMenuGroup",
    "NavMenuImportButton",
    "NavMenuItem",
    "NavMenuTab",
    "NavigationIconChoices",
    "NavigationWeightChoices",
    "Not",
    "ObjectDetailContent",
    "ObjectFieldsPanel",
    "ObjectTextPanel",
    "ObjectsTablePanel",
    "Omitted",
    "Panel",
    "PermissionsMixin",
    "PostButton",
    "SectionChoices",
    "StaticField",
    "StatsPanel",
    "Tab",
    "TabbedGroups",
    "TemplateExtension",
    "TextPanel",
    "Titles",
    "ViewNameBreadcrumbItem",
    "When",
    "context_object_attr",
    "flatten_context",
    "get_absolute_url",
    "queryset_to_nested_dict_keys_as_series",
    "queryset_to_nested_dict_records_as_series",
    "render_component_template",
)
