# Generated by Django 5.2.17 on 2026-09-04 04:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0011_alter_user_default_saved_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "permission policy",
                "verbose_name_plural": "permission policies",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="objectpermission",
            name="object_types",
            field=models.ManyToManyField(
                limit_choices_to=models.Q(
                    models.Q(
                        ("app_label__in", ["admin", "auth", "contenttypes", "sessions", "taggit", "users"]),
                        _negated=True,
                    ),
                    models.Q(("app_label", "admin"), ("model__in", ["logentry"])),
                    models.Q(("app_label", "auth"), ("model__in", ["group"])),
                    models.Q(
                        ("app_label", "users"),
                        (
                            "model__in",
                            [
                                "objectpermission",
                                "permissionpolicy",
                                "policyassignment",
                                "policyparameter",
                                "policyrule",
                                "token",
                                "user",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                related_name="object_permissions",
                to="contenttypes.contenttype",
            ),
        ),
    ]
