# Generated by Django 5.2.17 on 2026-09-04 04:01

import uuid

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0012_permission_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyParameter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z][a-z0-9_]*$",
                                "Parameter names must start with a lowercase letter and contain only lowercase letters, digits and underscores.",
                            )
                        ],
                    ),
                ),
                ("kind", models.CharField(max_length=20)),
                ("multiple", models.BooleanField(default=False)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="users.permissionpolicy",
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "policy parameter",
                "ordering": ["policy", "name"],
                "unique_together": {("policy", "name")},
            },
        ),
    ]
