# Generated by Django 5.2.17 on 2026-09-04 04:01

import uuid

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0013_policy_parameter"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("actions", nautobot.core.models.fields.JSONArrayField(base_field=models.CharField(max_length=30))),
                (
                    "constraint_template",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "path_map",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(
                                ("app_label__in", ["admin", "auth", "contenttypes", "sessions", "taggit", "users"]),
                                _negated=True,
                            ),
                            models.Q(("app_label", "admin"), ("model__in", ["logentry"])),
                            models.Q(("app_label", "auth"), ("model__in", ["group"])),
                            models.Q(
                                ("app_label", "users"),
                                (
                                    "model__in",
                                    [
                                        "objectpermission",
                                        "permissionpolicy",
                                        "policyassignment",
                                        "policyparameter",
                                        "policyrule",
                                        "token",
                                        "user",
                                    ],
                                ),
                            ),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_rules",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rules", to="users.permissionpolicy"
                    ),
                ),
            ],
            options={
                "verbose_name": "policy rule",
                "ordering": ["policy", "content_type"],
                "unique_together": {("policy", "content_type")},
            },
        ),
    ]
