# Generated by Django 5.2.17 on 2026-09-04 04:01

import uuid

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0015_permission_policy_seed_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "parameter_values",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("groups", models.ManyToManyField(blank=True, related_name="policy_assignments", to="auth.group")),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to="users.permissionpolicy",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(blank=True, related_name="policy_assignments", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "policy assignment",
                "ordering": ["name"],
            },
        ),
    ]
