# Generated by Django 5.2.17 on 2026-08-31 21:43

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectchange",
            name="object_data",
            field=models.JSONField(
                blank=True, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True
            ),
        ),
    ]
