# Generated by Django 5.2.16 on 2026-08-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="relationshipassociation",
            index=models.Index(fields=["source_type", "source_id", "relationship"], name="relassoc_src_obj_rel_idx"),
        ),
        migrations.AddIndex(
            model_name="relationshipassociation",
            index=models.Index(
                fields=["destination_type", "destination_id", "relationship"], name="relassoc_dst_obj_rel_idx"
            ),
        ),
    ]
