# Generated by Django 5.2.16 on 2026-08-03 01:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0145_objectmetadata_assigned_object_type_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobhook",
            name="conditions",
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name="jobhook",
            name="scope_filter",
            field=models.JSONField(
                blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
        migrations.AddField(
            model_name="webhook",
            name="conditions",
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name="webhook",
            name="scope_filter",
            field=models.JSONField(
                blank=True, default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
