# Generated by Django 5.2.17 on 2026-08-20 02:57

import uuid

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion

import nautobot.core.celery.encoders
import nautobot.extras.models.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0147_changelog_archive_storage"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("mode", models.CharField(default="include", max_length=16)),
                (
                    "scope_filter",
                    models.JSONField(
                        default=dict, editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("max_age_days", models.PositiveIntegerField(blank=True, null=True)),
                ("weight", models.PositiveSmallIntegerField(default=100)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_rules",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "retention rule",
                "verbose_name_plural": "retention rules",
                "ordering": ["weight", "name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
