# Generated by Django 5.2.17 on 2026-08-20 02:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("extras", "0147_changelog_optional_legacy_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("model_label", models.CharField(db_index=True, max_length=255)),
                ("period_key", models.CharField(db_index=True, max_length=16)),
                ("label", models.CharField(max_length=255)),
                ("period_granularity", models.CharField(default="year", max_length=16)),
                ("time_start", models.DateTimeField()),
                ("time_end", models.DateTimeField()),
                ("row_count", models.PositiveBigIntegerField(default=0)),
                ("last_rotated_time", models.DateTimeField(blank=True, null=True)),
                ("is_period_closed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "archive segment",
                "verbose_name_plural": "archive segments",
                "ordering": ["model_label", "-period_key"],
                "unique_together": {("model_label", "period_key")},
            },
        ),
    ]
